monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
